### ISSUE TITLE
p $cN still prints the old attr/cursor format

### ISSUE THREAD

**Issue by arichardson** [CTSRD-CHERI/gdb#17]
It would be nice if p $c17 would print the capability with bounds in the same way as `info registers`: `c17: 0x000000004015b06c [rxR,0x4015b040-0x4015b088]`

**Comment by bsdjhb** [comment]
There isn't an easy hook to override printing of a register's value.  I could perhaps change the type of capability registers to not be a struct but be a pointer, but I think you wouldn't be able to get to the raw register values anymore if I did that (e.g. 'p $c17.cursor' would no longer work).  However, you can cast the register to a pointer to get the pretty output, e.g. 'p (void *)$c17'

**Comment by bsdjhb** [comment]
I've changed this now so it pretty prints by default.  The individual "fields" of a capability you can no longer get to, but p/x will give you a raw hexdump of all the bytes.

Fixed in 603d49fa7305344796fb47470c874deb7a793fe7.

**Comment by davidchisnall** [comment]
Is it possible to pretty-print the capability registers?  This doesn't seem to be documented anywhre.

**Comment by bsdjhb** [comment]
Current gdb pretty prints them by default for purecap.  (Hybrid is a bit broken until I teach GDB that pointers can be different sizes).  In older GDB versions, 'p (void *)$c<mumble>' pretty prints them in purecap.

**Comment by nicolasjms** [comment]
Right now if you do p $c17 you will get this result:
$4 = (void *) 0x4034e94c <arena_dalloc+140> [rxR,0x401c0000-0x40454000]

Alexander suggested something like p (($cap_valid >> REGNUM) & 1)`. to print the tag bit, but having everything displayed at once would be ideal.

**Comment by bsdjhb** [comment]
Yes, I assumed the 'metadata' was the pretty print.  It turns out it is hard to include tags in the pretty-print format as the pretty-print format is applied to any pointer whether in memory or a register (and the pretty-printer doesn't really know what the source of the pointer is, it just gets the array of bytes).  GDB isn't currently aware of memory tags (nor do we store them in core dumps or have a way to get them via ptrace()), so the pretty printer can't reliably get access to the tag associated with the pointer.  I realize it would be ideal, but it is a lot of work to get there.
